version: '3.8'

services:
  php:
    image: ghcr.io/mathisDlmr/tutut:latest
    container_name: tutut
    ports:
      - "8000:8000"
    env_file:
      - .env.production
    volumes:
      - ./documents:/var/www/html/storage/app/private
      - ./logs:/var/www/html/storage/logs
      - ./.env.production:/var/www/html/.env
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000", "||", "exit", "1"]
      interval: 1m
      timeout: 30s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: tutut-nginx
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./documents:/var/www/html/storage/app/private
      - ./logs:/var/www/html/storage/logs
      - ./.env.production:/var/www/html/.env
    restart: always
