apiVersion: v1
kind: Secret
metadata:
  name: tutut-secrets
  namespace: tutut
type: Opaque
# Les valeurs ci-dessous sont encodées en base64.
# Générer avec : echo -n "valeur" | base64
# IMPORTANT : Remplacer ces valeurs avant le déploiement (ou utiliser SealedSecrets)
stringData:
  MYSQL_ROOT_PASSWORD: "changeme-root-password"
  MYSQL_DATABASE: "tutut"
  MYSQL_USER: "tutut"
  MYSQL_PASSWORD: "changeme-tutut-password"
  APP_KEY: "base64:XAxOQhy4yWYxh3m5n7cQy3PWTvREk20OsxfaMihxhLQ="
  OAUTH_CLIENT_ID: ""
  OAUTH_CLIENT_SECRET: ""
  API_UTCRAWL_KEY: "c83e8819-3c4c-4b9a-ad4c-e41845596c60"
